-
  version: 1.21.{build}
  platform: Any CPU
  configuration: Release
  branches:
    only:
      - release
  build:
    publish_nuget: true
  before_build:
  - cmd: nuget restore MiOP\MiOP.sln
  after_test:
  - cmd: nuget pack "MiOP\MiOP.nuspec" -Version %APPVEYOR_BUILD_VERSION%
  artifacts:
  - path: '*.nupkg'
    name: NuGetPackage
    
  - path: 'MiOP\bin\$(configuration)\MiOP.*'
    name: Plugin

  deploy:
  - provider: NuGet
    api_key:
      secure: IVtCkzUyoWfB41SzwMVeaYMMXwCLHjvzY7k6QW7K1GGpo8cwlN280QHWtD+qQFvp
    artifact: NuGetPackage
    on:
      platform: Any CPU
      configuration: Release