-
  version: 1.21.{build}
  platform: Any CPU
  configuration: Release
  branches:
    only:
      - release
  build:
    publish_nuget: true
  before_build:
  - cmd: nuget restore MiOP\MiOP.sln
  after_build:
  - cmd: nuget pack "MiOP\MiOP.nuspec" -Version %APPVEYOR_BUILD_VERSION%
  - cmd: 7z a MiOP.zip MiOP\bin\Release\MiOP.dll
  artifacts:
  - path: '*.nupkg'
    name: NuGetPackage
    
  - path: '**/MiOP.zip'
    name: Plugin

  deploy:
  - provider: NuGet
    api_key:
      secure: sky4reJa4/VtLojp12Mjjlzouz2Fq4lQtMK7fFNGnVQnhKKyhS1FcxHOjM81jV0i
    artifact: NuGetPackage
    on:
      platform: Any CPU
      configuration: Release